sonar.projectKey=mrTelnor_home-page
sonar.organization=mrtelnor

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.venv/**,**/venv/**,frontend/src/components/ui/**
sonar.coverage.exclusions=**/tests/**,**/alembic/**,frontend/src/components/ui/**
